<?php

return [
    [
        "title" => "Villa stile Barocco in riva mare con piscina 4 posti auto",
        "price" => 650,
        "slug" => "Villa-stile-Barocco-in-riva-mare-con-piscina-4-posti-auto2",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 11,
        "bed_number" => 5,
        "bath_number" => 3,
        "mq_value" => 400,
        "address" => "via dell alemagna 258",
        "lat" => 40.822311,
        "category_id" => 1,
        "long" => 14.051086,
        "visible" => true
    ],
    [
        "title" => "Attico stile Moderno centro citta Parcheggio",
        "price" => 400,
        "slug" => "Attico-stile-Moderno-centro-citta-Parcheggio3",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 8,
        "bed_number" => 4,
        "category_id" => 2,
        "bath_number" => 2,
        "mq_value" => 300,
        "address" => "piazza Giorgio V. 752",
        "lat" => 45.429834,
        "long" => 9.154851,
        "visible" => true
    ],
    [
        "title" => "Cottage montagna con servizio funivia",
        "price" => 1200,
        "slug" => "Cottage-montagna-con-servizio-funivia4",
        'cover_img' => '//via.placeholder.com/150',
        "category_id" => 5,
        "room_number" => 14,
        "bed_number" => 7,
        "bath_number" => 3,
        "mq_value" => 500,
        "address" => "viale Stati Uniti 122",
        "lat" => 42.429834,
        "long" => 10.154851,
        "visible" => true
    ],
    [
        "title" => "Villa Bella",
        "price" => 1000,
        "slug" => "Villa-Bella3",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 5,
        "category_id" => 4,
        "bed_number" => 10,
        "bath_number" => 4,
        "mq_value" => 500,
        "address" => "Via Roma 1",
        "lat" => 45.464204,
        "long" => 9.189982,
        "visible" => true
    ],
    [
        "title" => "Palazzo d'Oro",
        "price" => 2000,
        "slug" => "Palazzo-d'Oro2",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 8,
        "category_id" => 8,
        "bed_number" => 16,
        "bath_number" => 6,
        "mq_value" => 700,
        "address" => "Via della Libertà 2",
        "lat" => 41.902198,
        "long" => 12.496295,
        "visible" => true
    ],
    [
        "title" => "Luxury Mansion in Beverly Hills",
        "price" => 2500,
        "slug" => "Luxury-Mansion-in-Beverly-Hills2",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 15,
        "bed_number" => 10,
        "category_id" => 7,
        "bath_number" => 8,
        "mq_value" => 1000,
        "address" => "123 Main St",
        "lat" => 34.0736204,
        "long" => -11.4003563,
        "visible" => true
    ],
    [
        "title" => "Elegant Villa in Monaco",
        "price" => 2000,
        "slug" => "Elegant-Villa-in-Monaco2",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 12,
        "bed_number" => 8,
        "category_id" => 4,
        "bath_number" => 6,
        "mq_value" => 800,
        "address" => "456 Ocean Dr",
        "lat" => 43.7310535,
        "long" => 7.4197205,
        "visible" => true
    ],
    [
        "title" => "Luxury Apartment in Milan",
        "price" => 1000,
        "slug" => "Luxury-Apartment-in-Milan2",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 8,
        "bed_number" => 4,
        "category_id" => 3,
        "bath_number" => 3,
        "mq_value" => 500,
        "address" => "789 Seine River",
        "lat" => 48.8566101,
        "long" => 2.3514992,
        "visible" => true
    ],
    [
        "title" => "Luxury Penthouse con vista panoramica sulla città",
        "price" => 800,
        "slug" => "Luxury-Penthouse-con-vista-panoramica-sulla-città2",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 7,
        "bed_number" => 4,
        "category_id" => 5,
        "bath_number" => 2,
        "mq_value" => 300,
        "address" => "via delle stelle 56",
        "lat" => 41.900021,
        "long" => 12.496789,
        "visible" => true
    ],
    [
        "title" => "Chalet in montagna con vista mozzafiato",
        "price" => 550,
        "slug" => "Chalet-in-montagna-con-vista-mozzafiato3",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 9,
        "bed_number" => 6,
        "category_id" => 6,
        "bath_number" => 3,
        "mq_value" => 250,
        "address" => "via delle cime 128",
        "lat" => 45.678234,
        "long" => 7.865673,
        "visible" => true
    ],
    [
        "title" => "Appartamento moderno in centro città",
        "price" => 500,
        "slug" => "Appartamento-moderno-in-centro-città3",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 4,
        "bed_number" => 2,
        "category_id" => 5,
        "bath_number" => 1,
        "mq_value" => 150,
        "address" => "via dei fiori 23",
        "lat" => 43.765432,
        "long" => 11.256789,
        "visible" => true
    ],
    [
        "title" => "Villa con giardino privato e piscina",
        "price" => 700,
        "slug" => "Villa-con-giardino-privato-e-piscina3",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 8,
        "category_id" => 9,
        "bed_number" => 4,
        "bath_number" => 2,
        "mq_value" => 450,
        "address" => "via delle rose 98",
        "lat" => 44.123789,
        "long" => 10.987645,
        "visible" => true
    ],
    [
        "title" => "Appartamento moderno con terrazza panoramica",
        "price" => 450,
        "slug" => "Appartamento-moderno-con-terrazza-panoramica3",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 5,
        "category_id" => 4,
        "bed_number" => 2,
        "bath_number" => 1,
        "mq_value" => 150,
        "address" => "piazza della repubblica 15",
        "lat" => 41.893318,
        "long" => 12.482921,
        "visible" => true
    ],
    [
        "title" => "Casa colonica in campagna con giardino privato",
        "price" => 900,
        "slug" => "Casa-colonica-in-campagna-con-giardino-privato3",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 8,
        "category_id" => 7,
        "bed_number" => 4,
        "bath_number" => 2,
        "mq_value" => 300,
        "address" => "via delle querce 2",
        "lat" => 43.857759,
        "long" => 11.179249,
        "visible" => true
    ],
    [
        "title" => "Loft industrial con vista sul fiume",
        "price" => 550,
        "slug" => "Loft-industrial-con-vista-sul-fiume3",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 4,
        "category_id" => 8,
        "bed_number" => 2,
        "bath_number" => 1,
        "mq_value" => 200,
        "address" => "ponte vecchio 20",
        "lat" => 43.776324,
        "long" => 11.253052,
        "visible" => true
    ],
    [
        "title" => "Lussuoso appartamento moderno con vista città",
        "price" => 400,
        "slug" => "Lussuoso-appartamento-moderno-con-vista-città4",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 8,
        "category_id" => 3,
        "bed_number" => 4,
        "bath_number" => 2,
        "mq_value" => 300,
        "address" => "corso Vittorio Emanuele 21",
        "lat" => 41.900536,
        "long" => 12.487244,
        "visible" => true
    ],
    [
        "title" => "Rustico con giardino e piscina in campagna",
        "price" => 500,
        "slug" => "Rustico-con-giardino-e-piscina-in-campagna4",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 6,
        "bed_number" => 4,
        "category_id" => 1,
        "bath_number" => 2,
        "mq_value" => 200,
        "address" => "via degli ulivi 78",
        "lat" => 43.909337,
        "long" => 10.774424,
        "visible" => true
    ],
    [
        "title" => "Chalet in montagna con sauna e vista panoramica",
        "price" => 800,
        "slug" => "Chalet-in-montagna-con-sauna-e-vista-panoramica4",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 10,
        "category_id" => 3,
        "bed_number" => 6,
        "bath_number" => 3,
        "mq_value" => 400,
        "address" => "strada della montagna 54",
        "lat" => 46.073326,
        "long" => 11.123529,
        "visible" => true
    ],
    [
        "title" => "Appartamento con terrazza vista mare",
        "price" => 450,
        "slug" => "Appartamento-con-terrazza-vista-mare4",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 7,
        "bed_number" => 4,
        "category_id" => 3,
        "bath_number" => 2,
        "mq_value" => 250,
        "address" => "via del mare 99",
        "lat" => 43.716667,
        "long" => 10.4,
        "visible" => true
    ],
    [
        "title" => "Casa in stile provenzale con piscina privata",
        "price" => 700,
        "slug" => "Casa-in-stile-provenzale-con-piscina-privata4",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 9,
        "bed_number" => 5,
        "category_id" => 6,
        "bath_number" => 3,
        "mq_value" => 350,
        "address" => "rue des lavandes 43",
        "lat" => 43.806866,
        "long" => 6.484947,
        "visible" => true
    ],
    [
        "title" => "Appartamento in centro città con parcheggio",
        "price" => 400,
        "slug" => "Appartamento-in-centro-città-con-parcheggio4",
        'cover_img' => '//via.placeholder.com/150',
        "room_number" => 6,
        "bed_number" => 3,
        "category_id" => 4,
        "bath_number" => 2,
        "mq_value" => 200,
        "address" => "piazza delle erbe 12",
        "lat" => 45.464294,
        "long" => 9.189982,
        "visible" => true
    ]
];