<?php

return [
    [
        "title" => "Villa stile Barocco in riva mare con piscina 4 posti auto",
        "price" => 650,
        "room_number" => 11,
        "bed_number" => 5,
        "toilet_number" => 3,
        "mq_area" => 400,
        "address" => "via dell alemagna 258",
        "latitude" => 40.822311,
        "longitude" => 14.051086,
        "visible" => "true",
    ],
    [
        "title" => "Attico stile Moderno centro citta Parcheggio",
        "price" => 400,
        "room_number" => 8,
        "bed_number" => 4,
        "toilet_number" => 2,
        "mq_area" => 300,
        "address" => "piazza Giorgio V. 752",
        "latitude" => 45.429834,
        "longitude" => 9.154851,
        "visible" => "true",
    ],
    [
        "title" => "Cottage montagna con servizio funivia",
        "price" => 1200,
        "room_number" => 14,
        "bed_number" => 7,
        "toilet_number" => 3,
        "mq_area" => 500,
        "address" => "viale Stati Uniti 122",
        "latitude" => 42.429834,
        "longitude" => 10.154851,
        "visible" => "true",
    ],
    [
        "title" => "Villa Bella",
        "price" => 1000,
        "room_number" => 5,
        "bed_number" => 10,
        "toilet_number" => 4,
        "mq_area_area" => 500,
        "address" => "Via Roma 1",
        "latitude" => 45.464204,
        "longitude" => 9.189982,
        "visible" => "true",
    ],
    [
        "title" => "Palazzo d'Oro",
        "price" => 2000,
        "room_number" => 8,
        "bed_number" => 16,
        "toilet_number" => 6,
        "mq_area" => 700,
        "address" => "Via della Libertà 2",
        "latitude" => 41.902198,
        "longitude" => 12.496295,
        "visible" => "true",
    ],
    [
        "title" => "Palazzo d'Oro",
        "price" => 2000,
        "room_number" => 8,
        "bed_number" => 16,
        "toilet_number" => 6,
        "mq_area" => 700,
        "address" => "Via della Libertà 2",
        "latitude" => 41.902198,
        "longitude" => 12.496295,
        "visible" => "true",
    ],

    [
        "title" => "Luxury Mansion in Beverly Hills",
        "price" => 2500,
        "rooms" => 15,
        "beds" => 10,
        "toilet_number" => 8,
        "mq_area" => 1000,
        "address" => "123 Main St",
        "latitude" => 34.0736204,
        "longitude" => -11.4003563,
        "visible" => "true",
    ],
    [
        "title" => "Elegant Villa in Monaco",
        "price" => 2000,
        "rooms" => 12,
        "beds" => 8,
        "toilet_number" => 6,
        "mq_area" => 800,
        "address" => "456 Ocean Dr",
        "latitude" => 43.7310535,
        "longitude" => 7.4197205,
        "visible" => "true",
    ],
    [
        "title" => "Luxury Apartment in Paris",
        "price" => 1000,
        "rooms" => 8,
        "beds" => 4,
        "toilet_number" => 3,
        "mq_area" => 500,
        "address" => "789 Seine River",
        "latitude" => 48.8566101,
        "longitude" => 2.3514992,
        "visible" => "true",
    ],
    [
        "title" => "Luxury Penthouse con vista panoramica sulla città",
        "price" => 800,
        "room_number" => 7,
        "bed_number" => 4,
        "toilet_number" => 2,
        "mq_area" => 300,
        "address" => "via delle stelle 56",
        "latitude" => 41.900021,
        "longitude" => 12.496789,
        "visible" => "true",
    ],
    [
        "title" => "Chalet in montagna con vista mozzafiato",
        "price" => 550,
        "room_number" => 9,
        "bed_number" => 6,
        "toilet_number" => 3,
        "mq_area" => 250,
        "address" => "via delle cime 128",
        "latitude" => 45.678234,
        "longitude" => 7.865673,
        "visible" => "true",
    ],
    [
        "title" => "Appartamento moderno in centro città",
        "price" => 500,
        "room_number" => 4,
        "bed_number" => 2,
        "toilet_number" => 1,
        "mq_area" => 150,
        "address" => "via dei fiori 23",
        "latitude" => 43.765432,
        "longitude" => 11.256789,
        "visible" => "true",
    ],
    [
        "title" => "Villa con giardino privato e piscina",
        "price" => 700,
        "room_number" => 8,
        "bed_number" => 4,
        "toilet_number" => 2,
        "mq_area" => 450,
        "address" => "via delle rose 98",
        "latitude" => 44.123789,
        "longitude" => 10.987645,
        "visible" => "true",
    ],
    [
        "title" => "Appartamento moderno con terrazza panoramica",
        "price" => 450,
        "room_number" => 5,
        "bed_number" => 2,
        "toilet_number" => 1,
        "mq_area" => 150,
        "address" => "piazza della repubblica 15",
        "latitude" => 41.893318,
        "longitude" => 12.482921,
        "visible" => "true",
    ],
    [
        "title" => "Casa colonica in campagna con giardino privato",
        "price" => 900,
        "room_number" => 8,
        "bed_number" => 4,
        "toilet_number" => 2,
        "mq_area" => 300,
        "address" => "via delle querce 2",
        "latitude" => 43.857759,
        "longitude" => 11.179249,
        "visible" => "true",
    ],
    [
        "title" => "Loft industrial con vista sul fiume",
        "price" => 550,
        "room_number" => 4,
        "bed_number" => 2,
        "toilet_number" => 1,
        "mq_area" => 200,
        "address" => "ponte vecchio 20",
        "latitude" => 43.776324,
        "longitude" => 11.253052,
        "visible" => "true",
    ],
    [
        "title" => "Lussuoso appartamento moderno con vista città",
        "price" => 400,
        "room_number" => 8,
        "bed_number" => 4,
        "toilet_number" => 2,
        "mq_area" => 300,
        "address" => "corso Vittorio Emanuele 21",
        "latitude" => 41.900536,
        "longitude" => 12.487244,
        "visible" => "true",
    ],

    [
        "title" => "Rustico con giardino e piscina in campagna",
        "price" => 500,
        "room_number" => 6,
        "bed_number" => 4,
        "toilet_number" => 2,
        "mq_area" => 200,
        "address" => "via degli ulivi 78",
        "latitude" => 43.909337,
        "longitude" => 10.774424,
        "visible" => "true",
    ],
    [
        "title" => "Chalet in montagna con sauna e vista panoramica",
        "price" => 800,
        "room_number" => 10,
        "bed_number" => 6,
        "toilet_number" => 3,
        "mq_area" => 400,
        "address" => "strada della montagna 54",
        "latitude" => 46.073326,
        "longitude" => 11.123529,
        "visible" => "true",
    ],
    [
        "title" => "Appartamento con terrazza vista mare",
        "price" => 450,
        "room_number" => 7,
        "bed_number" => 4,
        "toilet_number" => 2,
        "mq_area" => 250,
        "address" => "via del mare 99",
        "latitude" => 43.716667,
        "longitude" => 10.4,
        "visible" => "true",
    ],
    [
        "title" => "Casa in stile provenzale con piscina privata",
        "price" => 700,
        "room_number" => 9,
        "bed_number" => 5,
        "toilet_number" => 3,
        "mq_area" => 350,
        "address" => "rue des lavandes 43",
        "latitude" => 43.806866,
        "longitude" => 6.484947,
        "visible" => "true",
    ],
    [
        "title" => "Appartamento in centro città con parcheggio",
        "price" => 400,
        "room_number" => 6,
        "bed_number" => 3,
        "toilet_number" => 2,
        "mq_area" => 200,
        "address" => "piazza delle erbe 12",
        "latitude" => 45.464294,
        "longitude" => 9.189982,
        "visible" => "true"
    ]
];